// Generated by Framer (1249b65)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import Image from 'next/image';
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
const cycleOrder = ["yrIu2Sstk"];
const variantClassNames = { yrIu2Sstk: "framer-v-10d98jw" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) => variant && Object.assign(nextOverrides, overrides[variant])
      );
  return nextOverrides;
}
const transitions = {
  default: { damping: 60, delay: 0, mass: 1, stiffness: 500, type: "spring" },
};
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition =
    value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const getProps = ({ height, id, image, width, ...props }) => {
  var ref;
  return {
    ...props,
    SVXX2h40W:
      (ref = image !== null && image !== void 0 ? image : props.SVXX2h40W) !==
        null && ref !== void 0
        ? ref
        : {
            src: new URL(
              "https://framerusercontent.com/images/1rnV14P8MhyhWjPOrSeUNIVvs.png"
              // "https://res.cloudinary.com/dcodwkhcg/image/upload/v1698601709/framer/chair.webp"
              ).href,
          },
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function Chair(props, ref) {
  const { activeLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, SVXX2h40W, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    gestureVariant,
    setGestureState,
    setVariant,
    transition,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "yrIu2Sstk",
    transitions,
    variant,
    variantClassNames,
  });
  const defaultLayoutId = React.useId();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(motion.div, {
      initial: variant,
      animate: variants,
      onHoverStart: () => setGestureState({ isHovered: true }),
      onHoverEnd: () => setGestureState({ isHovered: false }),
      onTapStart: () => setGestureState({ isPressed: true }),
      onTap: () => setGestureState({ isPressed: false }),
      onTapCancel: () => setGestureState({ isPressed: false }),
      className: cx("framer-zV98x", classNames),
      style: { display: "contents" },
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition,
        children: /*#__PURE__*/ _jsx(Image, {
          ...restProps,
          alt: "",
          fit: "fit",
          fill: true,
          loading: "eager",
          sizes: "(max-width: 1200px) 40.5vmax,(min-width: 1201px) 60vw, 60vw",
          ...toResponsiveImage(SVXX2h40W),
          className: cx("framer-10d98jw", className),
          "data-framer-name": "Variant 1",
          ref: ref,
          style: { ...style },
        }),
      }),
    }),
  });
});
const css = [
  '.framer-zV98x [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-zV98x .framer-4lbx2f { display: block; }",
  ".framer-zV98x .framer-10d98jw { height: 1577px; position: relative; width: 1577px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1577
 * @framerIntrinsicWidth 1577
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"SVXX2h40W":"image"}
 * @framerImmutableVariables false
 */
const Framereu4hs6EBv = withCSS(Component, css, "framer-zV98x");
Framereu4hs6EBv.displayName = "Chair";
Framereu4hs6EBv.defaultProps = { height: 1577, width: 1577 };
addPropertyControls(Framereu4hs6EBv, {
  SVXX2h40W: {
    __defaultAssetReference:
      "data:framer/asset-reference,0ApqjTBovBJEl24fqQX8PlJSRI.webp?originalFilename=chair.webp&preferredSize=auto",
    title: "Image",
    type: ControlType.ResponsiveImage,
  },
});
addFonts(Framereu4hs6EBv, []);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Framereu4hs6EBv",
      slots: [],
      annotations: {
        framerIntrinsicHeight: "1577",
        framerVariables: '{"SVXX2h40W":"image"}',
        framerContractVersion: "1",
        framerImmutableVariables: "false",
        framerIntrinsicWidth: "1577",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}',
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
export default Framereu4hs6EBv;
//# sourceMappingURL=./eu4hs6EBv.map
