// Generated by Framer (5ac62b5)
import { jsx as e, jsxs as r } from "react/jsx-runtime";
import {
  addFonts as t,
  addPropertyControls as a,
  ControlType as o,
  cx as i,
  RichText as rich,
  useLocaleInfo as n,
  useVariantState as d,
  withCSS as l,
} from "framer";
import { isSafari } from 'react-device-detect';
import {
  LayoutGroup as p,
  motion as f,
  MotionConfigContext as m,
} from "framer-motion";
import Image from "next/image";
import Link from 'next/link';
import * as u from "react";
let c = ["I447:517;355:380"],
  b = "framer-LFfFl",
  x = { "I447:517;355:380": "framer-v-n5ds9d" };
function g(e, ...r) {
  let t = {};
  return null == r || r.forEach((r) => r && Object.assign(t, e[r])), t;
}
let h = {
    default: { damping: 60, delay: 0, mass: 1, stiffness: 500, type: "spring" },
  },
  v = (e) =>
    "object" == typeof e && null !== e && "string" == typeof e.src
      ? e
      : "string" == typeof e
      ? { src: e }
      : void 0,
  y = ({ value: r, children: t }) => {
    let a = u.useContext(m),
      o = null != r ? r : a.transition,
      i = u.useMemo(() => ({ ...a, transition: o }), [JSON.stringify(o)]);
    return /*#__PURE__*/ e(m.Provider, { value: i, children: t });
  },
  R = ({ height: e, id: r, image: t, id:id, num: num, guest: guest, width: a, ...o }) => {
    var i;
    return {
      ...o,
      num: num,
      guest: guest,
      id: id,
      l4skPfBuN:
        null !== (i = null != t ? t : o.l4skPfBuN) && void 0 !== i
          ? i
          : {
              src: "https://framerusercontent.com/images/5ugqvHzekxvAbG6ckG5zUp0nJQ.png",
            },
    };
  },
  F = (e, r) => r.join("-") + e.layoutDependency,
  w = /*#__PURE__*/ u.forwardRef(function (t, a) {
    let { activeLocale: o } = n(),
      {
        style: l,
        className: m,
        layoutId: b,
        variant: g,
        l4skPfBuN: w,
        num: num,
        onReady: onReady,
        guest: guest,
        id: id,
        ...I
      } = R(t),
      {
        baseVariant: L,
        classNames: k,
        gestureVariant: N,
        setGestureState: j,
        setVariant: z,
        transition: P,
        variants: B,
      } = d({
        cycleOrder: c,
        defaultVariant: "I447:517;355:380",
        transitions: h,
        variant: g,
        variantClassNames: x,
      }),
      H = F(t, B),
      T = u.useRef(null),
      S = u.useId();
    const [isHovered, setHovered] = u.useState(false);
    const { ref,
      ...otherProps
    } = I;
    return /*#__PURE__*/ e(p, {
      id: null != b ? b : S,
      children: /*#__PURE__*/ e(f.div, {
        initial: g,
        animate: B,
        onHoverStart: () => setHovered(true),
        onHoverEnd: () => setHovered(false),
        onTapStart: () => j({ isPressed: !0 }),
        onTap: () => j({ isPressed: !1 }),
        onTapCancel: () => j({ isPressed: !1 }),
        className: i("framer-LFfFl", ...[], k),
        style: { display: "contents" },
        children: /*#__PURE__*/ e(y, {
          value: P,
          children: /*#__PURE__*/ r(Link, {
            ...otherProps,
            href: `/${num}`,
            id: id,
            scroll: false,
            className: i("framer-n5ds9d", m),
            style: { ...l },
            children: [
              r(f.div, {
                className: i("boxart", m),
                initial: false,
                transition: { type: "spring", stiffness: 100, damping: 15, mass: 1 },
                animate: {
                  transform: `translateY(${isHovered? "-10%" : "0%"}) ${isSafari ? "translateZ(0)" : ""}`,
                },
                children: [
                  r(f.div, {
                    className: i("color-underlay", m),
                    style: { position: "absolute" }
                  }),
                  r(f.div, {
                    initial: false,
                    transition: { type: "spring", stiffness: 100, damping: 15, mass: 1 },
                    style: { position: "absolute" },
                    animate: {
                      opacity: isHovered ? 1.0 : 0.95
                    }, children: w ? [
                      /*#__PURE__*/ e(Image, {
                        src: w,
                        ref: null != a ? a : T,
                        fill: true,
                        sizes: "17.5vmin",
                        quality: 80,
                        className: "homealbum-img",
                        loading:"eager",
                        placeholder:"blur",
                        blurDataURL:"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/+EAjEV4aWYAAE1NACoAAAAIAAGHaQAEAAAAAQAAABoAAAAAAASShgAHAAAAMwAAAFCgAQADAAAAAQABAACgAgAEAAAAAQAABLCgAwAEAAAAAQAABLAAAAAAQVNDSUkAAAAxLjczLjAtMjNPLTVCUk80UldQNDZQM1M0QkNSQjY2SlhRTDNBLjAuMi02AP/bAEMAAgEBAgEBAgICAgICAgIDBQMDAwMDBgQEAwUHBgcHBwYHBwgJCwkICAoIBwcKDQoKCwwMDAwHCQ4PDQwOCwwMDP/bAEMBAgICAwMDBgMDBgwIBwgMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDP/AABEIAAoACgMBIgACEQEDEQH/xAAXAAADAQAAAAAAAAAAAAAAAAACBAkK/8QAJxAAAgECBAUFAQAAAAAAAAAAAQIDBCEABQYRBwgJEjEUQUVRUmL/xAAUAQEAAAAAAAAAAAAAAAAAAAAF/8QAHREAAQIHAAAAAAAAAAAAAAAAAQAEAhJCU5Ki4v/aAAwDAQACEQMRAD8AnFmnSo4+JVS1EeXok0Ufp6gTV4jkUe4FrpYXO3jB0/Sa5gqqBJU01JMkihlkSd2WQEb9wIW4P3jQnUcvHD+XJ5XbQ2jmeWsad2OS0xLyWPeT2Xbe+/nDuS8DNEjJ6QDR2lgBCnxMH5H8YILl6K4cektO1tbFf//Z",
                        alt: "",
                        onLoad: () => {
                          if (onReady) onReady();
                        },
                        style: {
                          borderBottomLeftRadius: 2,
                          borderBottomRightRadius: 2,
                          borderTopLeftRadius: 2,
                          borderTopRightRadius: 2,
                          boxShadow:
                            "0px 3px 2px 0px rgba(0, 0, 0, 0.10000000149011612), 0px 4px 8px 0px rgba(0, 0, 0, 0.05000000074505806)",
                        },
                      })
                    ] : []
                  }),
                ]
              }),
              /*#__PURE__*/ e(f.div, {
                className: "framer-1eiicw1",
                "data-framer-name": "Album_support",
                layoutDependency: H,
                layoutId: "I447:517;355:380;359:462",
                style: {
                  backgroundColor: "rgb(224, 224, 224)",
                  borderBottomLeftRadius: 1,
                  borderBottomRightRadius: 1,
                  borderTopLeftRadius: 1,
                  borderTopRightRadius: 1,
                  boxShadow:
                    "0px 3px 2px 0px rgba(0, 0, 0, 0.10000000149011612), 0px 4px 8px 0px rgba(0, 0, 0, 0.05000000074505806)",
                },
              }),
              /*#__PURE__*/ e(rich, {
                __fromCanvasComponent: !0,
                children: /*#__PURE__*/ e(u.Fragment, {
                  children: /*#__PURE__*/ e(f.p, {
                    children: "MYRIAM LEROY",
                  }),
                }),
                style: { "--framer-font-family": "Futura Condensed Extra", "--framer-font-weight": 700, "--framer-text-color": "rgb(66, 56, 37)", "--framer-font-size": "0.805rem", "whiteSpace": "inherit", "--framer-text-alignment": "center", "marginTop": "1rem", "aspectRatio": "unset", "height": "min-content", "width": "100%"},
                text: guest.split(/\s(-|–)\s?/g)[0],
                verticalAlignment: "top",
                withExternalLayout: !0,
              })
            ],
          }),
        }),
      }),
    });
  }),
  I = [
    '.framer-LFfFl [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
    "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
    ".framer-LFfFl .framer-110p41z { display: block; }",
    ".framer-LFfFl .framer-n5ds9d { height: 104px; overflow: visible; position: relative; width: 104px; }",
    ".color-underlay { background-color: rgba(241, 241, 241, 1) }",
    ".framer-LFfFl .framer-rrg5dj { aspect-ratio: 1 / 1; bottom: var(--framer-aspect-ratio-supported, 0px); flex: none; height: 104px; left: 0px; position: absolute; right: 0px; top: 0px; }",
    ".framer-LFfFl .framer-1eiicw1 { bottom: -4px; flex: none; left: 32px; position: absolute; right: 32px; top: 100px; }",
  ],
  L = l(w, I, "framer-LFfFl");
export default L;
(L.displayName = "HomeAlbum"),
  (L.defaultProps = { height: 104, width: 104, num: 1, guest: "", id: null, }),
  a(L, {
    l4skPfBuN: {
      __defaultAssetReference:
        "data:framer/asset-reference,5ugqvHzekxvAbG6ckG5zUp0nJQ.png?originalFilename=Rectangle+4.png&preferredSize=auto",
      title: "Image",
      type: o.ResponsiveImage,
    },
  }),
  t(L, []);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramermtRhqnEgV",
      slots: [],
      annotations: {
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}',
        framerIntrinsicHeight: "104",
        framerContractVersion: "1",
        framerVariables: '{"l4skPfBuN":"image"}',
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "104",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./mtRhqnEgV.map
