// Generated by Framer (3d7e2b6)
import { jsx as e } from "react/jsx-runtime";
import {
  addFonts as r,
  addPropertyControls as t,
  ControlType as a,
  cx as o,
  useLocaleInfo as s,
  useVariantState as n,
  withCSS as d,
} from "framer";
import {
  LayoutGroup as f,
  motion as l,
  MotionConfigContext as p,
} from "framer-motion";
import i from "next/image";
import * as m from "react";
let c = { b37RCHR57: { hover: !0 } },
  u = ["b37RCHR57"],
  h = "framer-E1fZs",
  b = { b37RCHR57: "framer-v-nrqjoj" };
function v(e, ...r) {
  let t = {};
  return null == r || r.forEach((r) => r && Object.assign(t, e[r])), t;
}
let w = {
    default: { damping: 60, delay: 0, mass: 1, stiffness: 500, type: "spring" },
  },
  g = (e) =>
    "object" == typeof e && null !== e && "string" == typeof e.src
      ? e
      : "string" == typeof e
      ? { src: e }
      : void 0,
  j = ({ value: r, children: t }) => {
    let a = m.useContext(p),
      o = null != r ? r : a.transition,
      i = m.useMemo(() => ({ ...a, transition: o }), [JSON.stringify(o)]);
    return /*#__PURE__*/ e(p.Provider, { value: i, children: t });
  },
  y = ({ height: e, id: r, image: t, width: a, ...o }) => {
    var i;
    return {
      ...o,
      fDE1p5iGS:
        null !== (i = null != t ? t : o.fDE1p5iGS) && void 0 !== i
          ? i
          : {
              src: "https://framerusercontent.com/images/1cQdpjDMVfIHwcDhe6q9QrIAY.webp"
            },
    };
  },
  x = (e, r) => r.join("-") + e.layoutDependency,
  H = /*#__PURE__*/ m.forwardRef(function (r, t) {
    let { activeLocale: a } = s(),
      {
        style: d,
        className: p,
        layoutId: h,
        variant: H,
        fDE1p5iGS: R,
        ...D
      } = y(r),
      {
        baseVariant: I,
        classNames: E,
        gestureVariant: q,
        setGestureState: C,
        setVariant: Q,
        transition: S,
        variants: V,
      } = n({
        cycleOrder: u,
        defaultVariant: "b37RCHR57",
        enabledGestures: c,
        transitions: w,
        variant: H,
        variantClassNames: b,
      }),
      Z = x(r, V),
      A = m.useRef(null),
      M = m.useId();
    return /*#__PURE__*/ e(f, {
      id: null != h ? h : M,
      children: /*#__PURE__*/ e(l.div, {
        initial: H,
        animate: V,
        onHoverStart: () => C({ isHovered: !0 }),
        onHoverEnd: () => C({ isHovered: !1 }),
        onTapStart: () => C({ isPressed: !0 }),
        onTap: () => C({ isPressed: !1 }),
        onTapCancel: () => C({ isPressed: !1 }),
        className: o("framer-E1fZs", ...[], E),
        style: { display: "contents" },
        children: /*#__PURE__*/ e(j, {
          value: S,
          children: /*#__PURE__*/ e(l.div, {
            ...D,
            className: o("framer-nrqjoj", p),
            "data-framer-name": "Variant 1",
            ref: null != t ? t : A,
            style: {
              filter: "drop-shadow(0px 1px 11px rgba(0, 0, 0, 0.33))",
              rotate: 0,
              WebkitFilter: "drop-shadow(0px 1px 11px rgba(0, 0, 0, 0.33))",
              ...d,
            },
            children: /*#__PURE__*/ e(i, {
              alt: "",
              fill: true,
              sizes: "30vmin",
              ...g(R),
            }),
            variants: { "b37RCHR57-hover": { rotate: 2 } },
            ...v({ "b37RCHR57-hover": { "data-framer-name": void 0 } }, I, q),
          }),
        }),
      }),
    });
  }),
  R = [
    '.framer-E1fZs [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
    "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
    ".framer-E1fZs .framer-1cxgaw0 { display: block; }",
    ".framer-E1fZs .framer-nrqjoj { height: 297px; position: relative; width: 98px; }",
    ".framer-E1fZs .framer-v-nrqjoj .framer-nrqjoj { cursor: pointer; }",
    ".framer-E1fZs.framer-v-nrqjoj.hover .framer-nrqjoj { aspect-ratio: 0.3289588801399825 / 1; height: var(--framer-aspect-ratio-supported, 298px); }",
  ],
  D = d(H, R, "framer-E1fZs");
export default D;
(D.displayName = "Vinyl_CAF_d_Needle"),
  (D.defaultProps = { height: 298, width: 98 }),
  t(D, {
    fDE1p5iGS: {
      __defaultAssetReference:
        "data:framer/asset-reference,1cQdpjDMVfIHwcDhe6q9QrIAY.webp?originalFilename=needle_cut.webp&preferredSize=auto",
      title: "Image",
      type: a.ResponsiveImage,
    },
  }),
  r(D, []);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerZGaZ5r9JB",
      slots: [],
      annotations: {
        framerVariables: '{"fDE1p5iGS":"image"}',
        framerIntrinsicHeight: "298",
        framerImmutableVariables: "false",
        framerContractVersion: "1",
        framerIntrinsicWidth: "98",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"w6SCDqhGP":{"layout":["fixed","fixed"]}}}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./ZGaZ5r9JB.map
