// Generated by Framer (5ac62b5)
import Image from "next/image";
import React, { useState, useRef } from 'react';
import { motion } from "framer-motion";

function HomeAlbum({ height, id, image, num, guest, width, ...otherProps }) {
  const [isHovered, setHovered] = useState(false);
  const { style, className, variant, l4skPfBuN, onReady, imageRef, ...rest } = otherProps;

  const subject = guest.split(/\s(-|–)\s?/g)[2];
  guest = guest.split(/\s(-|–)\s?/g)[0];
  const newLine = guest.length < 22;
  
  const T = useRef(null);

  return (
      <div
        initial={variant}
        onMouseOver={() => setHovered(true)}
        onMouseOut={() => setHovered(false)}
        className={`framer-LFfFl ${className || ""}`}
        style={{ display: "contents" }}
      >
        <a id={id} href={`/${num}`}>
          <motion.div
            initial={false}
            className="boxart"
            transition={{ type: "spring", stiffness: 100, damping: 15, mass: 1 }}
            style={{
              height: "auto",
              width: "100%",
              aspectRatio: 1,
              transslateY: 0
            }}
            animate={{ opacity: isHovered ? 1.0 : 0.95, translateY: isHovered ? "-10%" : 0 }}
          >
            <div className="color-underlay" style={{
              height: "auto",
              width: "100%",
              aspectRatio: 1,
              backgroundColor: "rgb(241, 241, 241)",
            }} />
            {image && (
              <div style={{
                height: "auto",
                width: "100%",
                aspectRatio: 1,
                position: "absolute",
                top: 0,
                left: 0,
              }}>
                <Image
                  src={image}
                  ref={imageRef}
                  fill={true}
                  sizes="17.5vmin"
                  quality={80}
                  className="homealbum-img"
                  loading="eager"
                  placeholder="blur"
                  blurDataURL="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/+EAjEV4aWYAAE1NACoAAAAIAAGHaQAEAAAAAQAAABoAAAAAAASShgAHAAAAMwAAAFCgAQADAAAAAQABAACgAgAEAAAAAQAABLCgAwAEAAAAAQAABLAAAAAAQVNDSUkAAAAxLjczLjAtMjNPLTVCUk80UldQNDZQM1M0QkNSQjY2SlhRTDNBLjAuMi02AP/bAEMAAgEBAgEBAgICAgICAgIDBQMDAwMDBgQEAwUHBgcHBwYHBwgJCwkICAoIBwcKDQoKCwwMDAwHCQ4PDQwOCwwMDP/bAEMBAgICAwMDBgMDBgwIBwgMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDP/AABEIAAoACgMBIgACEQEDEQH/xAAXAAADAQAAAAAAAAAAAAAAAAACBAkK/8QAJxAAAgECBAUFAQAAAAAAAAAAAQIDBCEABQYRBwgJEjEUQUVRUmL/xAAUAQEAAAAAAAAAAAAAAAAAAAAF/8QAHREAAQIHAAAAAAAAAAAAAAAAAQAEAhJCU5Ki4v/aAAwDAQACEQMRAD8AnFmnSo4+JVS1EeXok0Ufp6gTV4jkUe4FrpYXO3jB0/Sa5gqqBJU01JMkihlkSd2WQEb9wIW4P3jQnUcvHD+XJ5XbQ2jmeWsad2OS0xLyWPeT2Xbe+/nDuS8DNEjJ6QDR2lgBCnxMH5H8YILl6K4cektO1tbFf//Z"
                  alt=""
                  style={{
                    borderBottomLeftRadius: 2,
                    borderBottomRightRadius: 2,
                    borderTopLeftRadius: 2,
                    borderTopRightRadius: 2,
                    left: 0,
                    top: 0,
                    boxShadow:
                      "0px 3px 2px 0px rgba(0, 0, 0, 0.10000000149011612), 0px 4px 8px 0px rgba(0, 0, 0, 0.05000000074505806)",
                  }}
                />
              </div>
            )}
          </motion.div>
          <div
            className="framer-1eiicw1"
            data-framer-name="Album_support"
            style={{
              position: "absolute",
              backgroundColor: "rgb(224, 224, 224)",
              borderBottomLeftRadius: 1,
              borderBottomRightRadius: 1,
              borderTopLeftRadius: 1,
              borderTopRightRadius: 1,
              boxShadow:
                "0px 3px 2px 0px rgba(0, 0, 0, 0.10000000149011612), 0px 4px 8px 0px rgba(0, 0, 0, 0.05000000074505806)",
            }}
          />
          <div
            style={{
              aspectRatio: "unset",
              height: "min-content",
              width: "108%",
              position: "absolute",
            }}
          >
            <p><span>{`${guest}${newLine ? "\n" : " "}`}</span><span>{`${subject}`}</span></p>
          </div>
      </a>
    </div>
  );
}

export default HomeAlbum;
